spring.application.name=ECF_HelpDesk_Pro

spring.datasource.url=jdbc:postgresql://localhost:5432/helpdeskpro
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
